variables:
    SLURM_CPUS_PER_TASK: 18
    SLURM_TIMELIMIT: "2:00:00"
    PULL_IMAGE: "YES"

build_core:
  tags:
    - kubernetes
  image: registry.gitlab.com/cscs-ci/stellar-group/hpx_docker/hpx-ccache
  script: 
    - ccache -o log_file=/root/ccache.log
    - ccache -s
    - cp -r $CI_PROJECT_DIR /code
    - |
      cmake /code \
            -B /build \
            -G "Ninja" \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_FLAGS="-O0 --coverage -fcolor-diagnostics" \
            -DCMAKE_EXE_LINKER_FLAGS="--coverage" \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=On \
            -DHPX_WITH_MALLOC=system \
            -DHPX_WITH_TOOLS=On \
            -DHPX_WITH_TESTS_HEADERS=On \
            -DHPX_WITH_COMPILER_WARNINGS=On \
            -DHPX_WITH_COMPILER_WARNINGS_AS_ERRORS=On \
            -DHPX_WITH_DEPRECATION_WARNINGS=On \
            -DHPX_WITH_THREAD_LOCAL_STORAGE=On \
            -DHPX_WITH_STACKTRACES_STATIC_SYMBOLS=On \
            -DHPX_WITH_STACKTRACES_DEMANGLE_SYMBOLS=Off \
            -DHPX_WITH_TESTS_DEBUG_LOG=On \
            -DHPX_WITH_TESTS_DEBUG_LOG_DESTINATION=/build/debug-log.txt \
            -DHPX_WITH_SPINLOCK_DEADLOCK_DETECTION=On
    - cd /build && ninja core tests examples
  after_script:
    - ccache -s
    - cp /root/ccache.log $CI_PROJECT_DIR/
    - cd /build
    - zip -0 ccov.zip `find . \( -name "*.gcno" -o -name "*.gcda" \) -print`;
    - mv ccov.zip $CI_PROJECT_DIR/
    #- grcov ccov.zip -s $CI_PROJECT_DIR -o $CI_PROJECT_DIR/coverage.info --llvm --ignore "/*" --ignore-not-existing -t lcov /build
  artifacts:
    when: always
    paths:
      - ccache.log
      - ccov.zip

#    - cd /build && ctest -j$(nproc) --output-on-failure --exclude-regex tests.unit.modules.include.api_future
#    - zip -0 ccov.zip `find . \( -name "*.gcno" -o -name "*.gcda" \) -print`;
#    - grcov ccov.zip -s $CI_PROJECT_DIR -o $CI_PROJECT_DIR/coverage.info --llvm --ignore "/*" --ignore-not-existing -t lcov /build
#  after_script:
#    - ccache -s
#  artifacts:
#    paths:
#    - ccov.zip
#    - coverage.info
