build:
  tags:
    - kubernetes
  image: registry.gitlab.com/cscs-ci/stellar-group/hpx_docker/hpx-ccache
  script: 
    - cp -r $CI_PROJECT_DIR /code
    - |
      cmake /code \
            -B /build \
            -G "Ninja" \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_FLAGS="-O0 --coverage -fcolor-diagnostics" \
            -DCMAKE_EXE_LINKER_FLAGS="--coverage" \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=On \
            -DHPX_WITH_MALLOC=system \
            -DHPX_WITH_TOOLS=On \
            -DHPX_WITH_TESTS_HEADERS=On \
            -DHPX_WITH_COMPILER_WARNINGS=On \
            -DHPX_WITH_COMPILER_WARNINGS_AS_ERRORS=On \
            -DHPX_WITH_DEPRECATION_WARNINGS=On \
            -DHPX_WITH_THREAD_LOCAL_STORAGE=On \
            -DHPX_WITH_STACKTRACES_STATIC_SYMBOLS=On \
            -DHPX_WITH_STACKTRACES_DEMANGLE_SYMBOLS=Off \
            -DHPX_WITH_TESTS_DEBUG_LOG=On \
            -DHPX_WITH_TESTS_DEBUG_LOG_DESTINATION=/build/debug-log.txt \
            -DHPX_WITH_SPINLOCK_DEADLOCK_DETECTION=On
    - cd /build && ninja core tests examples
    - ctest -j8 --timeout 240 --regex-exclude '.*distributed.tcp.*|tests.unit.component.launch_process|tests.regressions.threads.block_os_threads_1036'
  after_script:
    - ccache -s
    - cd /build
    - grcov . -s $CI_PROJECT_DIR -o $CI_PROJECT_DIR/coverage.info --llvm -t lcov
    - bash <(curl -s https://codecov.io/bash) -f $CI_PROJECT_DIR/coverage.info
    #- zip -0 ccov.zip `find . \( -name "*.gcno" -o -name "*.gcda" \) -print`;
  artifacts:
    when: always
    paths:
      - coverage.info
