# Copyright (c) 2020 Mikael Simberg
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: macOS CI

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew update && \
            brew install boost hwloc gperftools ninja && \
            brew upgrade cmake
    - name: Configure
      shell: bash
      run: |
          cmake \
              -H. \
              -Bbuild \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Debug \
              -DHPX_MPI_WITH_FUTURES=OFF \
              -DHPX_WITH_EXAMPLES=ON \
              -DHPX_WITH_TESTS=ON
    - name: Build
      shell: bash
      run: |
          cmake --build build --target all
          cmake --build build --target tests
    - name: Test
      shell: bash
      run: |
          cd build
          ctest --output-on-failure \
            --exclude-regex \
          "tests.examples.quickstart.1d_wave_equation|\
          tests.examples.transpose.transpose_block_numa|\
          tests.performance.local.wait_all_timings|\
          tests.regressions.components.distributed.tcp.bulk_new_3054|\
          tests.regressions.dynamic_counters_loaded_1508|\
          tests.regressions.lcos.wait_all_hang_1946|\
          tests.regressions.modules.collectives.distributed.tcp.broadcast_apply|\
          tests.regressions.modules.collectives.distributed.tcp.broadcast_unwrap_future_2885|\
          tests.regressions.modules.compute.parallel_fill_4132|\
          tests.regressions.util.distributed.tcp.zero_copy_parcels_1001_no_zero_copy_optimization|\
          tests.unit.modules.algorithms.default_construct|\
          tests.unit.modules.algorithms.destroy|\
          tests.unit.modules.execution.standalone_thread_pool_executor|\
          tests.unit.modules.resource_partitioner.used_pus|\
          tests.unit.modules.segmented_algorithms.distributed.tcp.partitioned_vector|\
          tests.unit.threads.distributed.tcp.thread_stacksize|\
          tests.unit.topology.numa_allocator"
